name: Merge JSON Files

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: echo "Merged pull request"

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: List files in the repo
        run: ls -R

      - name: Debug GITHUB_REF
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"

      - name: Merge JSON files
        run: |
          echo "Current ref: ${GITHUB_REF##*/}"
          if [[ "${GITHUB_HEAD_REF}" == *"topic-request"* ]]; then
            echo "Executing merge.py topic"
            python merge.py topic
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add topic/topics.json
            git commit -m "Added requested topic"
            git push
          elif [[ "${GITHUB_HEAD_REF}" == *"service-account-request"* ]]; then
            python merge.py service_account
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add service_account/service_accounts.json.json
            git commit -m "Added requested service account"
            git push
          fi
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
