name: Merge JSON Files

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: echo "Merged pull request"

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Merge JSON files
        run: |
          temp_main_json=$(mktemp)
          
          jq -n '{ "topics": [] }' > "$temp_main_json"
          
          for dir in topics; do
            for file in $(find "$dir" -name '*.json'); do
              jq --argfile new_json "$file" '.topics += [$new_json]' "$temp_main_json" > tmp.$$.json && mv tmp.$$.json "$temp_main_json"
              rm "$file"
            done