name: Merge JSON Files

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: echo "Merged pull request"

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Merge JSON files
        run: |
          if [[ "${GITHUB_REF##*/}" == *"topic-request"* ]]; then
            python merge_json.py topic
          elif [[ "${GITHUB_REF##*/}" == *"service-account-request"* ]]; then
            python merge_json.py service_account
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add topic/topics.json
          git commit -m "Added requested topics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
